### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by MarcKunst** [MartijnKeesmaat/frontend-data#1]
- [x] Concept beschrijving is niet meer up to date. Er staat nu functional programming en zins opbouw is vreemd.
- [x] Data informatie toevoegen. Ik citeer razpudding: 
"Vergeet niet in je readme te beschrijven wat je met foute of lege waardes doet!
Ik zou onder het kopje data eerst de collectie beschrijven, dan welk deel jij daaruit gebruikt, inclusief welke variabelen. Dan hoe een object uit de oorspronkelije sparql data eruit ziet, dan een linkje naar hoe je dat hebt opgeschoond en getransformeerd en onder dat linkje het nieuwe object."

**Comment by MartijnKeesmaat** [comment]
did the things
