### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by MarcKunst** [MartijnKeesmaat/frontend-data#2]
- [x] Ik mis een concept beschrijving in de wiki

- [x] Volgens mij moet er nog een pagina worden toegevoegd waarin je jou ervaring en understanding van D3 beschrijft.

Beschrijving van gebruikte code is duidelijk beschreven. Ook de update functie is helder. Lekker gewerkt G unit

**Comment by MartijnKeesmaat** [comment]
did the things
